language: generic

cache:
  directories:
    # General SwiftPM
    - .build
    # Danger Swift plugins
    - ~/.danger-swift

osx_image: xcode11

install:
  - bundle install
  - node -v
  - npm install -g danger@7.1.4
script:
  - swift run --package-path Tools/Bootstrap/ Bootstrap .
  - danger-swift ci
