disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - file_length
  - force_cast
  - function_body_length
  - line_length
  - nesting
  - type_name
  - force_try
  - cyclomatic_complexity
  - trailing_comma
  - large_tuple
  - multiple_closures_with_trailing_closure
  - fallthrough
  - no_fallthrough_only
  - generic_type_name

opt_in_rules:
  - overridden_super_call

type_body_length:
  - 600 # warning
  - 700 # error

colon:
  flexible_right_spacing: true

# Lints for missing calls to `super` in methods where this is expected.
overridden_super_call:
  included:
    # All the default methods
    - "*"
    # Service
    - start()
    # CommonViewControllerProtocol
    - setupViews()
    - setupBindings()
    - appWillResignActive()
    - appDidBecomeActive()
    - appDidEnterBackground()
    - appWillEnterForeground()

excluded:
  - Carthage
