on: pull_request

name: PullRequest
jobs:
  test:
    name: UnitTest
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache
        uses: actions/cache@v1.0.2
        id: carthage
        with:
          path: Carthage/Build
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          repo-token: ${{ secrets.GITHUB_ACTION_TOKEN }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: swift run --package-path Tools/Bootstrap/ Bootstrap .

      - name: Build and test
        run: |
          xcodebuild clean test -workspace SwiftCommunity.xcworkspace -scheme SwiftCommunity -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          bash <(curl -s https://codecov.io/bash)
        env:
          destination: ${{ matrix.destination }}

      - name: Danger
        run: swift run danger-swift ci
